---
name: Activity

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/metrics.yaml"

permissions:
  contents: write

jobs:
  app-activity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.repository == PSDTools/${{ github.ACTION_REPOSITORY }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      app-repository-people_svg: metrics/people/app-repository.svg
      app_followup_svg: metrics/followup/app_followup.svg
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 📈 App Metrics
        uses: gh-metrics/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10 # v3.34
        with:
          filename: ${{ env.app_followup_svg }}
          template: repository
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header, activity,community,repositories
          repo: app
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugins_errors_fatal: yes
      - name: 📈 App People Metrics
        uses: gh-metrics/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10 # v3.34
        with:
          filename: ${{ env.app-repository-people_svg }}
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          template: repository
          repo: app
          plugin_people: yes
          plugin_people_types: contributors, stargazers
          plugins_errors_fatal: yes

  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: metrics
    if: github.repository == PSDTools/${{ github.ACTION_REPOSITORY }}
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      metrics_svg: metrics/metrics.svg
      repositories_metrics_svg: metrics/repositories_metrics.svg
      followup_svg: metrics/followup/followup.svg
      org-people_svg: metrics/people/org-people.svg
      projects_svg: metrics/projects/projects.svg
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 📈 Projects Metrics
        uses: gh-metrics/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10 # v3.34
        with:
          filename: ${{ env.projects_svg }}
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 10
          plugins_errors_fatal: yes
      - name: 📈 Org Metrics
        uses: gh-metrics/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10 # v3.34
        with:
          filename: ${{ env.metrics_svg }}
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header
          plugin_introduction: yes
          plugin_traffic: yes
          plugins_errors_fatal: yes
      - name: 📈 Repos Metrics
        uses: gh-metrics/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10 # v3.34
        with:
          filename: ${{ env.repositories_metrics_svg }}
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: repositories
          plugins_errors_fatal: yes
      - name: 📈 PRs/Issues Metrics
        uses: gh-metrics/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10 # v3.34
        with:
          filename: ${{ env.followup_svg }}
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugins_errors_fatal: yes
