---
name: Activity

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [.github/workflows/metrics.yaml]

permissions:
  contents: write

jobs:
  metrics-activity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.repository == PSDTools/${{ github.ACTION_REPOSITORY }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      projects_svg: metrics/projects/projects.svg
      org-people_svg: metrics/people/org-people.svg
      app-repository-people_svg: metrics/people/app-repository.svg
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: ${{ env.projects_svg }}
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 10
          plugins_errors_fatal: yes
      - uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: ${{ env.app-repository-people_svg }}
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          template: repository
          repo: app
          plugin_people: yes
          plugin_people_types: contributors, stargazers
          plugins_errors_fatal: yes

  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: metrics
    if: github.repository == PSDTools/${{ github.ACTION_REPOSITORY }}
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      metrics_svg: metrics/metrics.svg
      repositories_metrics_svg: metrics/repositories_metrics.svg
      followup_svg: metrics/followup/followup.svg
      app_followup_svg: metrics/followup/app_followup.svg
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: ${{ env.metrics_svg }}
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header
          plugin_introduction: yes
          plugin_traffic: yes
          plugins_errors_fatal: yes
      - uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: ${{ env.repositories_metrics_svg }}
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: repositories
          plugins_errors_fatal: yes
      - uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: ${{ env.followup_svg }}
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugins_errors_fatal: yes
      - uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: ${{ env.app_followup_svg }}
          template: repository
          token: ${{ secrets.GH_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header, activity,community,repositories
          repo: app
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugins_errors_fatal: yes
