---
# This workflow warns of repos that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Stale Repo Identifier

on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [.github/workflows/stale_repos.yaml]

jobs:
  stale:
    name: Find Stale Repos
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: 🥖 Run stale_repos tool
        uses: github/stale-repos@c1d46fea2b9c52f4f8daefab7282328f620c232c # v1.6.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORGANIZATION: ${{ vars.ORGANIZATION }}
          INACTIVE_DAYS: 100
      - name: 👀 Look for an existing issue
        id: last-issue
        uses: micalevisk/last-issue-action@044e1cb7e9a4dde20e22969cb67818bfca0797be # v2.0.0
        # Find the last updated closes issue with a `stale-repos` label:
        with:
          state: closed
          labels: stale-repos
      - name: ✉️ Create issue
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4.0.1
        with:
          title: Stale Repository Report
          content-filepath: ./stale_repos.md
          assignees: "lishaduck"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          labels: |
            stale-repos
