---
# This workflow warns of repos that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Stale Repo Identifier

on:
  schedule:
  - cron: "0 14 1 * *"
  workflow_dispatch:

jobs:
  stale:
    name: Find Stale Repos
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: docker://ghcr.io/github/stale_repos:v1.4.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        organization: "PSDTools"
        INACTIVE_DAYS: 100
    
    - name: Lok for an existing issue
      id: last-issue
      uses: micalevisk/last-issue-action@v2
      # Find the last updated open issue with a `automated-issue` label:
      with:
        state: open
        labels: stale-repos
    
    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4.0.1
      with:
        title: Stale Repository Report
        content-filepath: ./stale_repos.md
        assignees: "lishaduck"
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ steps.last-issue.outputs.issue_number }}
        labels: |
          stale-repos
