---
name: ♻️ Sync Labels

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/sync-labels.yaml"
      - ".github/labels.yaml"

permissions: {}

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Sync Labels
        uses: srealmoreno/label-sync-action@850ba5cef2b25e56c6c420c4feed0319294682fd # v2.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-file: https://raw.githubusercontent.com/PSDTools/.github/main/.github/labels.yaml
          clean-labels: false
          repositories: |
            PSDTools/app
            PSDTools/psdtools.github.io
